/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author david
 */
public class EleccionFichero2 extends javax.swing.JPanel {

    private int tipoTablero;
    private boolean miVariable;
    private boolean cortana;

    /**
     * Creates new form Nickname2
     */
    public EleccionFichero2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_nickname2 = new javax.swing.JPanel();
        btnHalo2 = new javax.swing.JButton();
        btnCortana2 = new javax.swing.JButton();
        btnTablero2 = new javax.swing.JButton();
        btnTablero1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnLimpiarTodo = new javax.swing.JButton();
        btnHalo = new javax.swing.JButton();
        btnCortana1 = new javax.swing.JButton();
        label_nickname = new javax.swing.JLabel();

        panel_nickname2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHalo2.setBackground(new java.awt.Color(255, 153, 102));
        btnHalo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Halo.png"))); // NOI18N
        btnHalo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHalo2ActionPerformed(evt);
            }
        });
        panel_nickname2.add(btnHalo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 80, 80));

        btnCortana2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cortan.png"))); // NOI18N
        btnCortana2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCortana2ActionPerformed(evt);
            }
        });
        panel_nickname2.add(btnCortana2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 80, 80));

        btnTablero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/MiniTablero2.png"))); // NOI18N
        btnTablero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablero2ActionPerformed(evt);
            }
        });
        panel_nickname2.add(btnTablero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 170, 140));

        btnTablero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/miniTablero.png"))); // NOI18N
        btnTablero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablero1ActionPerformed(evt);
            }
        });
        panel_nickname2.add(btnTablero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 180, 140));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Atras.gif"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel_nickname2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 590, 200, 90));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Play (1).gif"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(540, 560));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_nickname2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 200, 90));

        btnLimpiarTodo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnLimpiarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Limpiar.gif"))); // NOI18N
        btnLimpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTodoActionPerformed(evt);
            }
        });
        panel_nickname2.add(btnLimpiarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 200, 90));

        btnHalo.setBackground(new java.awt.Color(255, 153, 102));
        btnHalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Halo.png"))); // NOI18N
        btnHalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaloActionPerformed(evt);
            }
        });
        panel_nickname2.add(btnHalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 80, 80));

        btnCortana1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cortan.png"))); // NOI18N
        btnCortana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCortana1ActionPerformed(evt);
            }
        });
        panel_nickname2.add(btnCortana1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 80, 80));

        label_nickname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FicheroTablero2.png"))); // NOI18N
        panel_nickname2.add(label_nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_nickname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_nickname2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHalo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHalo2ActionPerformed
        EleccionFichero2 p2 = new EleccionFichero2();
        p2.miVariable = true;
        BancoDeVariables.setHalo2(p2.miVariable);
        BancoDeVariables.setfichero2(1);
        cortana = false;
        btnCortana2.setVisible(false);                                     

    }//GEN-LAST:event_btnHalo2ActionPerformed

    private void btnTablero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablero2ActionPerformed
        tipoTablero = 2;
        btnTablero1.setVisible(false);
    }//GEN-LAST:event_btnTablero2ActionPerformed

    private void btnTablero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablero1ActionPerformed
        tipoTablero = 1;
        btnTablero2.setVisible(false);
    }//GEN-LAST:event_btnTablero1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        MododeJuego b4 = new MododeJuego();
        showPanel5(b4.getFondo2());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tipoTablero == 1){
                    Date fechaHoraActual = new Date();
                    Timestamp HoraFecha = new Timestamp(fechaHoraActual.getTime());
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    String fecha_inicio = dateFormat.format(HoraFecha);
                    BancoDeVariables.setfecha_inicio(fecha_inicio);
                    
                    int tablero=1;
                    BancoDeVariables.setidTablero(tablero);
            
                    tablero tab1 = new tablero();
                    showPanel5(tab1.getFondo5());

        }
        if (tipoTablero == 2){
                    Date fechaHoraActual = new Date();
                    Timestamp HoraFecha = new Timestamp(fechaHoraActual.getTime());
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    String fecha_inicio = dateFormat.format(HoraFecha);
                    BancoDeVariables.setfecha_inicio(fecha_inicio);
                    
                    int tablero=2;
                    BancoDeVariables.setidTablero(tablero);
            
                    tablero2 tab2 = new tablero2();
                    showPanel5(tab2.getFondo5());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTodoActionPerformed
        limpiarFicha();
    }//GEN-LAST:event_btnLimpiarTodoActionPerformed

    private void btnHaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaloActionPerformed
        EleccionFichero2 p1 = new EleccionFichero2();
        p1.miVariable = true;
        BancoDeVariables.setHalo(p1.miVariable);
        BancoDeVariables.setfichero(1);
        cortana = false;
        btnCortana1.setVisible(false);
    }//GEN-LAST:event_btnHaloActionPerformed

    private void btnCortana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCortana1ActionPerformed
        EleccionFichero2 p12 = new EleccionFichero2();
        p12.miVariable = false;
        cortana = true;
        BancoDeVariables.setfichero(2);
        BancoDeVariables.setHalo(p12.miVariable);
        btnHalo.setVisible(false);
    }//GEN-LAST:event_btnCortana1ActionPerformed

    private void btnCortana2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCortana2ActionPerformed
        EleccionFichero2 p22 = new EleccionFichero2();
        p22.miVariable = false;
        BancoDeVariables.setfichero2(2);
        cortana = true;
        BancoDeVariables.setHalo2(p22.miVariable);
        btnHalo2.setVisible(false);
    }//GEN-LAST:event_btnCortana2ActionPerformed
    public JPanel getFondo4() {
        return panel_nickname2;
    }
    private void showPanel5(JPanel p){
        p.setSize(1150, 694);
        p.setLocation(0, 0);
        panel_nickname2.removeAll();
        panel_nickname2.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        panel_nickname2.revalidate();
        panel_nickname2.repaint();
    }
    private void limpiarFicha() {
            btnCortana1.setVisible(true);
            btnHalo.setVisible(true);
            btnCortana2.setVisible(true);
            btnHalo2.setVisible(true);
            btnTablero1.setVisible(true);
            btnTablero2.setVisible(true);
            tipoTablero = 0;
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCortana1;
    private javax.swing.JButton btnCortana2;
    private javax.swing.JButton btnHalo;
    private javax.swing.JButton btnHalo2;
    private javax.swing.JButton btnLimpiarTodo;
    private javax.swing.JButton btnTablero1;
    private javax.swing.JButton btnTablero2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel label_nickname;
    private javax.swing.JPanel panel_nickname2;
    // End of variables declaration//GEN-END:variables
}
