


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JPanel;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author david
 */
public class EleccionFichero1 extends javax.swing.JPanel {

    /**
     * Creates new form EleccionFichero1
     */
    private  boolean halo;
    private  boolean cortana;
    private boolean miVariable;
    private tablero tab1;
    private int tipoTablero = 0;
    
    public EleccionFichero1() {
        initComponents();
       // panel_nickname.setFocusable(true);
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_nickname = new javax.swing.JPanel();
        btnLimpiarTodo = new javax.swing.JButton();
        btnTablero1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnMasterchief = new javax.swing.JButton();
        btnCortana = new javax.swing.JButton();
        btnTablero2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1150, 694));

        panel_nickname.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiarTodo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnLimpiarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Limpiar.gif"))); // NOI18N
        btnLimpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTodoActionPerformed(evt);
            }
        });
        panel_nickname.add(btnLimpiarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 200, 90));

        btnTablero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/miniTablero.png"))); // NOI18N
        btnTablero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablero1ActionPerformed(evt);
            }
        });
        panel_nickname.add(btnTablero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 180, 180));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Atras.gif"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel_nickname.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 200, 90));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Play (1).gif"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(540, 560));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_nickname.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 200, 90));

        btnMasterchief.setBackground(new java.awt.Color(255, 153, 102));
        btnMasterchief.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Halo.png"))); // NOI18N
        btnMasterchief.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterchiefActionPerformed(evt);
            }
        });
        panel_nickname.add(btnMasterchief, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 80, 80));

        btnCortana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cortan.png"))); // NOI18N
        btnCortana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCortanaActionPerformed(evt);
            }
        });
        panel_nickname.add(btnCortana, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 80, 80));

        btnTablero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/MiniTablero2.png"))); // NOI18N
        btnTablero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablero2ActionPerformed(evt);
            }
        });
        panel_nickname.add(btnTablero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 170, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FicheroTablero.png"))); // NOI18N
        panel_nickname.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_nickname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        if (tipoTablero == 1){                    
                    Date fechaHoraActual = new Date();
                    Timestamp HoraFecha = new Timestamp(fechaHoraActual.getTime());
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    String fecha_inicio = dateFormat.format(HoraFecha);
                    BancoDeVariables.setfecha_inicio(fecha_inicio);
                    
                    int tablero=1;
                    BancoDeVariables.setidTablero(tablero); 
                    
                    tablero tab1 = new tablero();
                    showPanel4(tab1.getFondo5());
                    
                    
        }
        if (tipoTablero == 2){
                    Date fechaHoraActual = new Date();
                    Timestamp HoraFecha = new Timestamp(fechaHoraActual.getTime());
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    String fecha_inicio = dateFormat.format(HoraFecha);
                    BancoDeVariables.setfecha_inicio(fecha_inicio);
                                        
                    int tablero=2;
                    BancoDeVariables.setidTablero(tablero);   
                    
                    tablero2 tab2 = new tablero2();
                    showPanel4(tab2.getFondo5());                    
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void btnMasterchiefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterchiefActionPerformed
            miVariable = true;
            BancoDeVariables.setHalo(miVariable);
            BancoDeVariables.setfichero(1);
            cortana = false;
            btnCortana.setVisible(false);
    }//GEN-LAST:event_btnMasterchiefActionPerformed

    private void btnCortanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCortanaActionPerformed
        cortana = true;
        miVariable = false;   
        BancoDeVariables.setHalo(miVariable);
        BancoDeVariables.setfichero(2);
        btnMasterchief.setVisible(false);
    }//GEN-LAST:event_btnCortanaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MododeJuego b4 = new MododeJuego();
        showPanel4(b4.getFondo2());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnTablero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablero1ActionPerformed
        tipoTablero = 1;
        btnTablero2.setVisible(false);        
    }//GEN-LAST:event_btnTablero1ActionPerformed

    private void btnLimpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTodoActionPerformed
        limpiarFicha();
    }//GEN-LAST:event_btnLimpiarTodoActionPerformed

    private void btnTablero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablero2ActionPerformed
        tipoTablero = 2;
        btnTablero1.setVisible(false);
    }//GEN-LAST:event_btnTablero2ActionPerformed
    public JPanel getFondo3() {
        return panel_nickname;
    }
    private void showPanel4(JPanel p){
        p.setSize(1150, 694);
        p.setLocation(0, 0);
        panel_nickname.removeAll();
        panel_nickname.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        panel_nickname.revalidate();
        panel_nickname.repaint();
    }
    private void limpiarFicha() {
        btnCortana.setVisible(true);
        btnMasterchief.setVisible(true);
        btnTablero1.setVisible(true);
        btnTablero2.setVisible(true);
        tipoTablero = 0;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCortana;
    private javax.swing.JButton btnLimpiarTodo;
    private javax.swing.JButton btnMasterchief;
    private javax.swing.JButton btnTablero1;
    private javax.swing.JButton btnTablero2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_nickname;
    // End of variables declaration//GEN-END:variables
}
